import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-admin'

interface CartItem {
  productId: string
  quantity: number
  unitPriceCents: number
}

export async function POST(req: NextRequest) {
  try {
    const { weekendId, slotId, cart, userId } = await req.json() as {
      weekendId: string
      slotId: string
      cart: CartItem[]
      userId: string
    }

    if (!weekendId || !slotId || !cart?.length || !userId) {
      return NextResponse.json({ error: 'Paramètres manquants' }, { status: 400 })
    }

    const totalNems = cart.reduce((s, item) => s + item.quantity, 0)
    const amountCents = cart.reduce((s, item) => s + item.quantity * item.unitPriceCents, 0)

    // 1. Insert the order (ref auto-generated by DB trigger, status='pending')
    const { data: order, error: orderError } = await supabaseAdmin
      .from('orders')
      .insert({
        profile_id: userId,
        weekend_id: weekendId,
        slot_id: slotId,
        status: 'pending',
        total_nems: totalNems,
        amount_cents: amountCents,
      })
      .select('id, ref')
      .single()

    if (orderError || !order) {
      console.error('Order insert error:', orderError)
      return NextResponse.json({ error: 'Impossible de créer la commande' }, { status: 500 })
    }

    // 2. Insert order lines
    const lines = cart.map((item) => ({
      order_id: order.id,
      product_id: item.productId,
      quantity: item.quantity,
      unit_price_cents: item.unitPriceCents,
    }))

    const { error: linesError } = await supabaseAdmin.from('order_lines').insert(lines)
    if (linesError) {
      console.error('Order lines insert error:', linesError)
      return NextResponse.json({ error: "Impossible d'enregistrer les produits" }, { status: 500 })
    }

    // 3. Increment slots.orders_count (non-blocking)
    const slotRead = await supabaseAdmin.from('slots').select('orders_count').eq('id', slotId).single()
    if (!slotRead.error && slotRead.data) {
      await supabaseAdmin
        .from('slots')
        .update({ orders_count: (slotRead.data.orders_count ?? 0) + 1 })
        .eq('id', slotId)
    }

    // 4. Decrement weekends.stock_left by totalNems (non-blocking)
    const wkRead = await supabaseAdmin.from('weekends').select('stock_left').eq('id', weekendId).single()
    if (!wkRead.error && wkRead.data) {
      await supabaseAdmin
        .from('weekends')
        .update({ stock_left: Math.max(0, (wkRead.data.stock_left ?? 0) - totalNems) })
        .eq('id', weekendId)
    }

    return NextResponse.json({ orderId: order.id, ref: order.ref })
  } catch (err) {
    console.error('Unexpected error in /api/orders:', err)
    return NextResponse.json({ error: 'Erreur serveur inattendue' }, { status: 500 })
  }
}
